// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HoLV4FMlJ7Y1qXup1zIvEAeKYRz9NjA',
    appId: '1:246772563645:web:42e09d38bce1f8ba1801d4',
    messagingSenderId: '246772563645',
    projectId: 'diole-41ab4',
    authDomain: 'diole-41ab4.firebaseapp.com',
    storageBucket: 'diole-41ab4.appspot.com',
    measurementId: 'G-RR44GD3S15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFQZcVUWDi7q6x_-p9q6xM-TAuxVNF5U',
    appId: '1:246772563645:android:e8e6461916a106021801d4',
    messagingSenderId: '246772563645',
    projectId: 'diole-41ab4',
    storageBucket: 'diole-41ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIb4CdfoeUUtZ2vo0aBw3nDYikx6Rrb0M',
    appId: '1:246772563645:ios:902f88e94fc0fce61801d4',
    messagingSenderId: '246772563645',
    projectId: 'diole-41ab4',
    storageBucket: 'diole-41ab4.appspot.com',
    iosBundleId: 'com.example.d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIb4CdfoeUUtZ2vo0aBw3nDYikx6Rrb0M',
    appId: '1:246772563645:ios:902f88e94fc0fce61801d4',
    messagingSenderId: '246772563645',
    projectId: 'diole-41ab4',
    storageBucket: 'diole-41ab4.appspot.com',
    iosBundleId: 'com.example.d',
  );
}
